/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_x264encoderdemo_YuvUtils */

#ifndef _Included_com_test_x264encoderdemo_YuvUtils
#define _Included_com_test_x264encoderdemo_YuvUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_x264encoderdemo_YuvUtils
 * Method:    yuv420Rotate90
 * Signature: ([BIII)V
 */
JNIEXPORT void JNICALL Java_com_test_x264encoderdemo_YuvUtils_yuv420Rotate90
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
